version: "3.9"

services:
  api-gateway:
    build:
      context: .
      dockerfile: ./api-gateway/Dockerfile
    container_name: api-gateway
    ports:
      - 8000:8000
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://lgtm:4317
    depends_on:
      - order
      - user

  order:
    build:
      context: .
      dockerfile: ./microservices/order/Dockerfile
    container_name: order-service
    ports:
      - 6002:6002
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://lgtm:4317
    depends_on:
      - lgtm

  user:
    build:
      context: .
      dockerfile: ./microservices/user/Dockerfile
    container_name: user-service
    ports:
      - 6001:6001
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://lgtm:4317
    depends_on:
      - lgtm

  lgtm:
    image: grafana/otel-lgtm:latest
    container_name: lgtm
    ports:
      - "3000:3000" # Grafana
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
