listenAddress: :8000
requestTimeout: 10s
routes:
  - name: User Service
    prefix: /user
    backendUrl: http://user:6001

  - name: Order Service
    prefix: /order
    backendUrl: http://order:6002
