listenAddress: localhost:8000
requestTimeout: 30s
routes:
  - name: User Service
    prefix: /user
    backendUrl: http://localhost:6001

  - name: Order Service
    prefix: /order
    backendUrl: http://localhost:6002
